# Discord Bot Settings
bot:
    enable: false
    # 디스코드 개발자 포털에서 발급받은 봇 토큰
    token: "YOUR_BOT_TOKEN_HERE"
    # 봇이 주로 활동할 서버(길드)의 ID
    guild-id: "YOUR_GUILD_ID_HERE"

# Discord OAuth2 Settings (for web dashboard, etc.)
# 디스코드 OAuth2 인증 정보 (웹 대시보드 연동 등 추가 기능에 사용)
discord-api:
    client-id: "YOUR_CLIENT_ID_HERE"
    client-secret: "YOUR_CLIENT_SECRET_HERE"
    redirect-url: "YOUR_REDIRECT_URI_HERE"

server:
    port: 8080

# Database Connection Settings
# 데이터베이스 연결 정보
database:
    host: "192.168.0.113"
    port: 3306
    username: "root"
    password: "YOUR_DB_PASSWORD_HERE"
    database: "Experiments"
