name: DiscordSyncX
version: '1.0-SNAPSHOT'
main: kr.doka.lab.discordsync.DiscordSyncPlugin
api-version: '1.21'
authors: [ DOKA1203 ]
bootstrapper: kr.doka.lab.discordsync.DiscordSyncPluginBootstrapper
loader: kr.doka.lab.discordsync.DiscordSyncPluginLoader
